app/controller/main/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020/12/3 14:06
# @Author  : cendeavor
# @File    : __init__.py.py
# @Software: PyCharm

from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/controller/main/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020/12/3 14:07
# @Author  : cendeavor
# @File    : views.py
# @Software: PyCharm

from app.service.tag_service import TagService
from app.service.data_service import DataService
from app.dto import Response
from flask import request, render_template, jsonify, flash, redirect, url_for
from flask_login import current_user, login_required, logout_user
from . import main

data_service = DataService()
symptoms = data_service.get_data(cname='symptoms')
tag_service = TagService()
data_gen = None


@main.route('/', methods=['GET', 'POST'])
@login_required
def index():
    """ 首页

    Returns:

    """
    tag_service.register(participant=current_user.username)
    global data_gen
    if not data_gen:  # 加上这句，不会重复打标；但是会遗漏打标。。为了工作量统计方便，还是加吧，大不了每晚重启
        data_gen = tag_service.generate_data()
    return redirect(url_for('main.next_user'))


@main.route('/next', methods=['GET'])
@login_required
def next_user():
    """ 标注下一个

    Returns:

    """
    try:
        data = next(data_gen)
    except Exception as e:
        return redirect(url_for("main.next_user"))
        # return render_template('/main/finish.html', stats=tag_service.stat_workload(
        #     participant=current_user.username))  # todo: test this line
    user_link = data['user_homepage']
    tweets = data['tweets']
    statistics = tag_service.stat_workload(participant=current_user.username)
    tweet_stats = data['tweet_stats']
    return render_template('/main/tagging.html', user_id=data['_id'], user_link=user_link, tweets=tweets,
                           symptoms=symptoms,
                           stats=statistics, tweet_stats=tweet_stats,
                           auto_detect=['insomnia'])


@main.route('/tag', methods=['GET', 'POST'])
@login_required
def tag():
    """ 打标

    Returns:

    """
    data = request.get_json()
    print(data)
    # TODO: 系统自动根据规则判别（tag_service）
    res = tag_service.tag(participant=current_user.username, data=data)
    return jsonify(Response.success('打标成功', res))


@main.route('/diagnosis-rules', methods=['GET', 'POST'])
@login_required
def rules():
    """ 打标

    Returns:

    """
    return render_template('/main/rules.html')


@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))


@main.route('/restart')
def restart():
    return render_template('/ops/restart.html')

app/templates/main/finish.html
{% extends 'base.html' %}

{% block body_content %}
<h1>恭喜你完成所有标注!</h1>
<h1>您已累计标注{{ stats.done_total }}，本轮标注{{ stats.done_cur }}，累计工作{{ stats.work_time }} </h1>
<a class="btn btn-primary btn-sm" href="{{ url_for('ops.restart') }}">重启</a>
{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block body_content %}
<h1>你终于来打标了！</h1>
{{ wtf.quick_form(form) }}
<a class="btn btn-primary btn-sm" href="{{ url_for('main.logout') }}">登出</a>
<!--<a class="btn btn-primary btn-sm" href="{{ url_for('main.next_user') }}">打标</a>-->
{% endblock %}

app/templates/main/rules.html
{% extends 'base.html' %}

{% block body_content %}
<p>在做所有事前，先点点右边的用户主页链接吧，如果看到简历中的（用户名/公司/简介）表明这个人是心理医生，就直接点第一条：<span style="color:deeppink"><b>心理医生</b></span>的单选框并点击保存
</p>
<p>用户推文栏的推文统计信息是给人留初步印象的，比如凌晨发帖比例高，那这个用户一定失眠；私密发帖多，证明这个用户贴隐藏了很多负面情绪的贴</p>
<p>判断为抑郁的条件：<br>1. 满足编号<span style="color:red"><b>第1条</b></span> <br>2. 满足<span
        style="color:orange"><b>第2或第3条</b></span>中的一个，以及至少5个症状</p><br>
<p>前三个<span style="color:lawngreen"><b>※号</b></span>所对应的条目是人为判断的，其中“医学确定”是留给医学生打的，闲杂人等勿用233</p><br>
<p>需要注意的是用户自查的（<span style="color:lawngreen"><b>非医学自述抑郁</b></span>）抑郁症和医院诊断的抑郁症（<span
        style="color:red"><b>非医学自述抑郁</b></span>）的区别</p>
{% endblock %}

app/templates/main/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello World</title>
</head>
<body>
    <h1>Hello World!</h1>
</body>
</html>